# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: ["master", "main"]
  push:
    branches: ["master", "main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run tests

  set-status:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set test status
        if: always()
        run: |
          STATUS=$(echo "${{ job.status }}" | tr -d '[:space:]')
          if [ "$STATUS" == "success" ]; then
            gh pr check --success --name "tests" --message "Tests passed"
          else
            gh pr check --failure --name "tests" --message "Tests failed"
          fi
